version: '3'

services:
  encrypt:
    build: ./NeudaTaskA
    volumes:
      - type: bind
        source: C:\Users\Liam\PycharmProjects\NeuedaTask2
        target: /jsonfileloc
      - type: volume
        source: datavolume
        target: /data

  decrypt:
    build: ./NeudaTaskB
    depends_on:
      - "encrypt"
    volumes:
      - type: volume
        source: datavolume
        target: /data

volumes:
  datavolume: {}

